// Generated by `npm run db:types`. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      foods: {
        Row: {
          barcode: string | null
          brand: string | null
          created_at: string
          default_serving_g: number | null
          external_id: string | null
          id: string
          image_url: string | null
          name: string
          name_de: string | null
          name_en: string | null
          name_pl: string | null
          nutrients: Json
          owner_id: string | null
          search_text: string | null
          source: string
          stores: string | null
          updated_at: string
          verified: boolean
        }
        Insert: {
          barcode?: string | null
          brand?: string | null
          created_at?: string
          default_serving_g?: number | null
          external_id?: string | null
          id?: string
          image_url?: string | null
          name: string
          name_de?: string | null
          name_en?: string | null
          name_pl?: string | null
          nutrients: Json
          owner_id?: string | null
          search_text?: string | null
          source: string
          stores?: string | null
          updated_at?: string
          verified?: boolean
        }
        Update: {
          barcode?: string | null
          brand?: string | null
          created_at?: string
          default_serving_g?: number | null
          external_id?: string | null
          id?: string
          image_url?: string | null
          name?: string
          name_de?: string | null
          name_en?: string | null
          name_pl?: string | null
          nutrients?: Json
          owner_id?: string | null
          search_text?: string | null
          source?: string
          stores?: string | null
          updated_at?: string
          verified?: boolean
        }
        Relationships: []
      }
      log_entries: {
        Row: {
          created_at: string
          food_id: string | null
          food_name: string
          grams: number
          id: string
          log_date: string
          meal: string
          nutrients: Json
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          food_id?: string | null
          food_name: string
          grams: number
          id?: string
          log_date: string
          meal: string
          nutrients: Json
          updated_at?: string
          user_id?: string
        }
        Update: {
          created_at?: string
          food_id?: string | null
          food_name?: string
          grams?: number
          id?: string
          log_date?: string
          meal?: string
          nutrients?: Json
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "log_entries_food_id_fkey"
            columns: ["food_id"]
            isOneToOne: false
            referencedRelation: "foods"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          birth_date: string | null
          created_at: string
          eat_back_factor: number
          energy_unit: string
          goal_kcal_delta: number
          health_data_consent_at: string | null
          height_cm: number | null
          neat_factor: number
          sex: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          birth_date?: string | null
          created_at?: string
          eat_back_factor?: number
          energy_unit?: string
          goal_kcal_delta?: number
          health_data_consent_at?: string | null
          height_cm?: number | null
          neat_factor?: number
          sex?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          birth_date?: string | null
          created_at?: string
          eat_back_factor?: number
          energy_unit?: string
          goal_kcal_delta?: number
          health_data_consent_at?: string | null
          height_cm?: number | null
          neat_factor?: number
          sex?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      weight_entries: {
        Row: {
          created_at: string
          id: string
          kg: number
          measured_on: string
          source: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          kg: number
          measured_on: string
          source?: string
          user_id?: string
        }
        Update: {
          created_at?: string
          id?: string
          kg?: number
          measured_on?: string
          source?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      search_foods: {
        Args: { max_results?: number; query: string }
        Returns: {
          barcode: string | null
          brand: string | null
          created_at: string
          default_serving_g: number | null
          external_id: string | null
          id: string
          image_url: string | null
          name: string
          name_de: string | null
          name_en: string | null
          name_pl: string | null
          nutrients: Json
          owner_id: string | null
          search_text: string | null
          source: string
          stores: string | null
          updated_at: string
          verified: boolean
        }[]
        SetofOptions: {
          from: "*"
          to: "foods"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      search_normalize: { Args: { value: string }; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

export type Profile = Tables<'profiles'>
export type Food = Tables<'foods'>
export type LogEntry = Tables<'log_entries'>
