#!/usr/bin/env node
/**
 * Convert the BLS 4.0 spreadsheet (German national nutrient database, Max Rubner-Institut)
 * into a SQL seed for public.foods.
 *
 * Source: https://www.blsdb.de (free to use, including for apps, since BLS 4.0).
 * Citation: Max Rubner-Institut (2025): Bundeslebensmittelschlüssel (BLS), Version 4.0.
 *           DOI: 10.25826/Data20251217-134202-0
 *
 * Usage: node scripts/import-bls.mjs path/to/BLS_4_0_Daten_2025_DE.xlsx
 * Output: supabase/seeds/foods_bls.sql
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import ExcelJS from 'exceljs';

const input = process.argv[2];
if (!input) {
  console.error('Usage: node scripts/import-bls.mjs path/to/BLS_4_0_Daten_2025_DE.xlsx');
  process.exit(1);
}
const output = fileURLToPath(new URL('../supabase/seeds/foods_bls.sql', import.meta.url));

// BLS component code -> our nutrient key (packages/core/src/nutrients.ts).
// BLS "CHO" is available carbohydrate (fibre excluded), matching EU labels.
const COMPONENTS = {
  ENERCC: 'energy_kcal',
  PROT625: 'protein_g',
  CHO: 'carbs_available_g',
  SUGAR: 'sugar_g',
  FAT: 'fat_g',
  FASAT: 'saturated_fat_g',
  FIBT: 'fiber_g',
  NA: 'sodium_mg',
};
const BATCH_SIZE = 500;

const workbook = new ExcelJS.Workbook();
await workbook.xlsx.readFile(input);
const sheet = workbook.worksheets[0];
const header = sheet.getRow(1).values.slice(1).map(String);

const column = (prefix) => {
  const index = header.findIndex((h) => h.startsWith(`${prefix} `));
  if (index === -1) throw new Error(`Column ${prefix} not found`);
  return index;
};
const codeCol = header.indexOf('BLS Code');
const deCol = header.indexOf('Lebensmittelbezeichnung');
const enCol = header.indexOf('Food name');
if (codeCol === -1 || deCol === -1 || enCol === -1) throw new Error('Name columns not found');
const nutrientCols = Object.entries(COMPONENTS).map(([code, key]) => [column(code), key]);

const sql = (value) => (value == null ? 'null' : `'${String(value).replace(/'/g, "''")}'`);
const round = (value) => Math.round(value * 100) / 100;

const rows = [];
for (let r = 2; r <= sheet.rowCount; r++) {
  const values = sheet.getRow(r).values.slice(1);
  const code = values[codeCol];
  const nameDe = values[deCol];
  const nameEn = values[enCol];
  if (!code || !nameEn) continue;

  const nutrients = {};
  for (const [col, key] of nutrientCols) {
    const value = values[col];
    // Empty cells are unknown values, not zero.
    if (typeof value === 'number' && Number.isFinite(value)) nutrients[key] = round(value);
  }
  if (nutrients.energy_kcal === undefined) continue;

  const name = String(nameEn).trim();
  rows.push(
    `(${sql('bls')}, ${sql(code)}, ${sql(name)}, ${sql(name)}, ${sql(String(nameDe).trim())}, ` +
      `${sql(JSON.stringify(nutrients))}::jsonb, true)`,
  );
}

const statements = [];
for (let i = 0; i < rows.length; i += BATCH_SIZE) {
  statements.push(
    'insert into public.foods (source, external_id, name, name_en, name_de, nutrients, verified) values\n' +
      rows.slice(i, i + BATCH_SIZE).join(',\n') +
      '\non conflict (source, external_id) do update set\n' +
      '  name = excluded.name, name_en = excluded.name_en, name_de = excluded.name_de,\n' +
      '  nutrients = excluded.nutrients, verified = excluded.verified;',
  );
}

writeFileSync(
  output,
  `-- Generated by scripts/import-bls.mjs from BLS 4.0 (Max Rubner-Institut, 2025). Do not edit by hand.\n` +
    `-- ${rows.length} foods.\n\n${statements.join('\n\n')}\n`,
);
console.log(`Wrote ${rows.length} foods to ${output}`);
